### ISSUE TITLE
tweet container not restricted to a max width?

### ISSUE THREAD

**Issue by slrls** [shashankmehta/greyshade#10]
Hey, really like your theme! This might not be a real issue, but maybe more of just a concern.

I noticed that the latest tweets text and banner currently aren't being bound a max % width. Long tweets don't wrap, so they end up pushing the div boundaries way outside div.mid-col. I'm a terrible noob at web design, but I couldn't convince myself that this was intentional. If I'm wrong, my bad!

I personally really didn't like it as I don't think we ought to be seeing any horizontal scroll bars in responsive designs. In _twitter.scss, I ended up adding "width:95%;" to the #banner to address the div containment issue and "word-wrap: break-word;" to the li element to get the entire tweet to show. Only catch is that the time stamp gets pushed to line 2 in these long tweets. I have it set up this way on my site iamscottrogers.com.

Great work otherwise!

**Comment by shashankmehta** [comment]
Thanks @slrls! It was unintentional and I have fixed it. My fix is slightly different from what you have done.
