### ISSUE TITLE
Push .mid-col to the bottom

### ISSUE THREAD

**Issue by matthewrobertson** [shashankmehta/greyshade#13]
On pages with little content, the `.mid-col` does not always make it to the bottom of the page and leaving a band on blue under it. See attached:
![Screen Shot 2013-02-05 at 5 42 18 PM](https://f.cloud.github.com/assets/644493/130063/7982f200-6ffe-11e2-8d1a-4a8f16c53e6f.png)

**Comment by matthewrobertson** [comment]
Also, I think related to this is right before the media-query kicks in to move the side column to the top, the image overlaps the right column a bit:
![Screen Shot 2013-02-05 at 5 43 13 PM](https://f.cloud.github.com/assets/644493/130069/c4e3d638-6ffe-11e2-86f1-6e37d5a2a0f2.png)

**Comment by matthewrobertson** [comment]
I fixed both of these issues by adding the following rules to my `_styles.scss` file:

```
body, html {
  height: 100%;
}

.container {
  position: relative;
  min-height: 100%;
}

.mid-col {
  position: absolute;
  right: 0;
  min-height: 100%;
  float: none;
}
```

(will try to create a proper pull request in a sec)

**Comment by matthewrobertson** [comment]
ps Thanks for creating such an awesome theme :+1:

**Comment by shashankmehta** [comment]
Thanks for the appreciation! 
PS: Waiting for your pull request :smile:
