### ISSUE TITLE
Support external-url linklog option

### ISSUE THREAD

**Issue by lencioni** [shashankmehta/greyshade#30]
The Octopress documentation discusses [using Octopress as a linklog](http://octopress.org/docs/blogging/linklog/).

According to their documentation, you simply need to add `external-url` to the post frontmatter as such:

```
external-url: http://opinionguy.com/post/uninformed-rant-vs-straw-man/
```

However, the theme dictates what effect this actually has. It seems that the greyshade theme doesn't do anything with this option.

**Comment by lencioni** [comment]
Here is a writeup detailing how someone added support for this to their theme: http://www.candlerblog.com/2012/01/30/octopress-linked-list/

**Comment by shashankmehta** [comment]
Octopress 2.1 natively supports linklog. https://gist.github.com/imathis/1812265
I don't think it is supposed to be part of themes.

**Comment by lencioni** [comment]
Ah yes, you appear to be correct. Thanks for the speedy response!
