### ISSUE TITLE
Customization Variable

### ISSUE THREAD

**Issue by endymuhardin** [shashankmehta/greyshade#35]
To further differentiate among Greyshade installation, consider adding variables for:
- left sidebar color
- midcol color
- font-family for headings
- font-family for article content

**Comment by shashankmehta** [comment]
I did think about this, mainly the color of sidebar. I wasn't sure about it back then but after seeing [this](http://blog.due.io/2013/octopress-theme-yinyang/#comment-932494960), I think I should add these options.

**Comment by rohitsinha54** [comment]
Looking ahead to these features. They will be really useful.
