### ISSUE TITLE
error while running rake generate command

### ISSUE THREAD

**Issue by pkmishra** [shashankmehta/greyshade#37]
$ rake generate
Generating Site with Jekyll
    error sass/screen.scss (Line 9 of sass/custom/_styles.scss: Undefined variable: "$img-border".)

**Comment by shashankmehta** [comment]
Did you install the default theme before installing greyshade?

**Comment by pkmishra** [comment]
Yes. The default theme was working fine then later I installed Reynard theme which is working fine with no issues.

**Comment by shashankmehta** [comment]
Try reinstalling the original theme and then install greyshade. I'm not able to recreate the issue.

**Comment by rafaellyra** [comment]
I have the same problem and resolved removing the sass folder and installing greyshade again.
