### ISSUE TITLE
Update Twitter API

### ISSUE THREAD

**Issue by cryptiklemur** [shashankmehta/greyshade#38]
https://github.com/shashankmehta/greyshade/blob/master/source/javascripts/twitter.js#L55.

Need to update to 1.1

**Comment by rodolfo42** [comment]
Agreed, but it's a bummer Twitter now requires OAuth for all public methods - including user timeline

see here: https://dev.twitter.com/discussions/11564

makes it impracticable to do a client-only JS solution from now on
this guy managed to do something, though:

http://jasonmayes.com/projects/twitterApi/

**Comment by shashankmehta** [comment]
This is still a very hack-y solution to the twitter OAuth problem. I'm marking this as wont-fix because it isn't worth the hassle. Sorry.
