### ISSUE TITLE
Gravatar needs jquery to work

### ISSUE THREAD

**Issue by rohitsinha54** [shashankmehta/greyshade#43]
Great work with the theme. It looks brilliant. I am using it for my personal website. 

I think the gravatar needs jquery to work. It didn't work for me just adding the email address in _config. 

The browser console shows error for jquery. So to fix it I just included jquery in the head section of source/_includes/head.html and it started working. 

I think it will be great if you can update the documentation to include this. 

Thanks.

**Comment by Kent1** [comment]
https://github.com/shashankmehta/greyshade/commit/a446e1538959833cf056cd27b88f86889a414d13
