### ISSUE TITLE
Does configuring Google Analytics in _config.yml work?

### ISSUE THREAD

**Issue by jcope2013** [shashankmehta/greyshade#50]
I listed my tracking id next to it but I can't seem to get it to work, shouldn't it generate the necessary script tag inside the bottom of my blog posts when I create a new post similar to how Disqus works after it get's configured, When I search through the whole folder, I can't find anything relating to Google Analytics except that one line

**Comment by miguelgraz** [comment]
I believe it is working properly, I'm seeing both the `{% include google_analytics.html %}` line in `greyshade/source/_includes/head.html` file and the `greyshade/source/_includes/google_analytics.html` file itself, looking to `google_analytics_tracking_id` variable.

Did you try re-generate the site? Take a look at the real-time feature on google analytics too, it can help perhaps.

**Comment by jcope2013** [comment]
this line was for some reason missing at the bottom of head.html file

{% include google_analytics.html %}

no idea why, hopefully that does it, I had the google_analytics.html file

still clueless to how that got deleted
