### ISSUE TITLE
Not able to add a new social feed on the left sidebar

### ISSUE THREAD

**Issue by rohitsinha54** [shashankmehta/greyshade#53]
I am trying to add Quora on the left sidebar.

Here are my changes:
https://github.com/rohitsinha54/greyshade/commit/cf0b9fdba3343127fa5dd715ee4342fdfc807a90

But its not getting reflecting on the website. Am I missing something ?

**Comment by shashankmehta** [comment]
Looks fine. If you have `quora_user` set in your `_config.yml` then it should appear in leftbar.

**Comment by rohitsinha54** [comment]
I have quora_user set in _config.yml but it doesn't seem to work at all. 

Here is snippet from my config:

![image](https://f.cloud.github.com/assets/1472867/1350021/e308ddb4-3701-11e3-9fb0-0d2f34a35bd9.png)

After the changes I am doing rake generate and rake preview. Do I need to do something else to make the changes in the theme show up ?

Thanks.

**Comment by rohitsinha54** [comment]
It works. I was forgetting to do 

> rake "install[greyshade]"

After changing the things in themes directory. 

Making pull request https://github.com/shashankmehta/greyshade/pull/55

Closing issue.
