### ISSUE TITLE
error sass/screen.scss

### ISSUE THREAD

**Issue by aladdin-im** [shashankmehta/greyshade#59]
```
rake generate
## Generating Site with Jekyll
    error sass/screen.scss (Line 2 of sass/_greyshade.scss: Invalid CSS after "@import ": expected file to import (string or url()), was "custom/_font.scss")
```

**Comment by rahilsondhi** [comment]
Yup I'm having the same issue

**Comment by aladdin-im** [comment]
I solved this problem, there are two ways to solve
1. Remove this line directly `@import custom/_font.scss` in `sass / _greyshade.scss`file.
    and custom `font-family` value.(e.g. `font-family: "Open Sans", "HelveticaNeue-Light","Helvetica Neue Light","Helvetica Neue",Helvetica,Arial,sans-serif;`)
2. Modify this line `@import custom/_font.scss` in `sass / _greyshade.scss`file.(e.g. `import "custom/_font.scss";`). and open comment line `//$serif: "Baskerville", serif;` in `custom/_font.scss` file.
The first method is more suitable for me.

**Comment by W1nd** [comment]
Thx! I just have worked it out!

**Comment by xautjzd** [comment]
@shashankmehta  I have the same problem

**Comment by alex-zige** [comment]
this should be PR request to the code base. people will get stuck every time.

**Comment by wjgilmore** [comment]
Ditto what @alex-zige said. I had the same problem, and resolved it by following @heqingbao's first suggestion.

**Comment by shashankmehta** [comment]
Thanks for reporting and confirming the bug. This has been fixed. I'm sorry for the trouble.
