### ISSUE TITLE
Embedding code using Gist plugin screws up alignment

### ISSUE THREAD

**Issue by emilsoman** [shashankmehta/greyshade#6]
Using the gist plugin and embedding code aligns all code text to "center".

Debugged a little and found this in the inherited style attributes of the code lines-

```
article .entry-content table td {
  text-align: center;
}
```

Tried with the classic theme and this is what I got -

```
caption, th, td {
  font-weight: normal;
  text-align: left;
}
```

**Comment by shashankmehta** [comment]
Github updated gist yesterday or so and that broke the embed feature somehow. It was working before. I'll fix this soon.

**Comment by Hotboards** [comment]
I'm sorry but i have the same issue, all my code is align to center o every gist. I am using joomla 3.0
