### ISSUE TITLE
'date/clock' can's show on my blog

### ISSUE THREAD

**Issue by wayne930242** [shashankmehta/greyshade#72]
![2017-03-03 16-24-08](https://cloud.githubusercontent.com/assets/5166321/23543596/d9bca60c-002d-11e7-974b-c396b422f32c.png)

my blog: http://wayneh.tw/
the repo: https://github.com/wayne930242/wayne930242.github.io

**Comment by liyongxin** [comment]
any ideas? same questions

**Comment by liyongxin** [comment]
@wayne930242
