### ISSUE TITLE
$greyshade text selection color

### ISSUE THREAD

**Issue by jsvensson** [shashankmehta/greyshade#9]
A possible suggestion to further differentiate different sites using Greyshade: change the text selection color to $greyshade. I'm using this [on my site](http://atomicplayboy.net/) as an example.

``` sass
::selection, ::-moz-selection, ::-webkit-selection
    background-color: $greyshade
    color: $color-background
```

![Screen Shot 2012-12-28 at 02 11 13](https://f.cloud.github.com/assets/450287/33435/7fc00ed8-508b-11e2-9928-0a0af8501b1c.png)

**Comment by shashankmehta** [comment]
A very nice suggestion! Thanks!
